### ISSUE TITLE
System.TypeInitializationException was unhandled

### ISSUE THREAD

**Issue by jbondhus** [zoho/books-dotnet-wrappers#2]
I get an exception when I run the following program.

```c#
ZohoBooks service = new ZohoBooks();
service.initialize(ZOHO_API_KEY, ZOHO_ORGANIZATION_ID);
ProjectsApi projects_api = service.GetProjectsApi();

Dictionary<object, object> search_query = new Dictionary<object, object>();

TimeEntryList entries = projects_api.GetTimeEnries(search_query);
```

```
System.TypeInitializationException was unhandled
  HResult=-2146233036
  Message=The type initializer for 'zohobooks.api.ProjectsApi' threw an exception.
  Source=books-dotnet
  TypeName=zohobooks.api.ProjectsApi
  StackTrace:
       at zohobooks.api.ProjectsApi..ctor(String auth_token, String organization_Id)
       at zohobooks.service.ZohoBooks.GetProjectsApi()
       at Toggle_Zoho_Sync.Program.Main(String[] args) in C:\Users\Jon\Documents\Code\C#\Toggle-Zoho-Sync\Toggle-Zoho-Sync\Program.cs:line 21
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
       HResult=-2146233036
       Message=The type initializer for 'zohobooks.api.Api' threw an exception.
       Source=books-dotnet
       TypeName=zohobooks.api.Api
       StackTrace:
            at zohobooks.api.ProjectsApi..cctor()
       InnerException: 
            FileName=Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
            FusionLog==== Pre-bind state information ===
LOG: DisplayName = Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
 (Fully-specified)
LOG: Appbase = file:///C:/Users/Jon/Documents/Code/C#/Toggle-Zoho-Sync/Toggle-Zoho-Sync/bin/Debug/
LOG: Initial PrivatePath = NULL
Calling assembly : books-dotnet, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\Users\Jon\Documents\Code\C#\Toggle-Zoho-Sync\Toggle-Zoho-Sync\bin\Debug\Toggle-Zoho-Sync.vshost.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Post-policy reference: Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
LOG: Attempting download of new URL file:///C:/Users/Jon/Documents/Code/C#/Toggle-Zoho-Sync/Toggle-Zoho-Sync/bin/Debug/Newtonsoft.Json.DLL.
WRN: Comparing the assembly name resulted in the mismatch: Major Version
ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.

            HResult=-2146234304
            Message=Could not load file or assembly 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
            Source=books-dotnet
            StackTrace:
                 at zohobooks.api.Api..cctor()
            InnerException: 
```

**Comment by hari-thalapaneni** [comment]
Dear jbondhus ,

The exception may be because of the version miss matching of the assembly Newtonsoft.Json . Kindly check the assembly Newtonsoft.Json .

Fell free to contact us on further if you are faced any difficulties or issues.

**Comment by jbondhus** [comment]
What assembly version is it supposed to be? I'm running 6.0.2, which is the oldest version available on NuGet. Perhaps the assembly reference requirement should be changed to 6.0.2?

![image](https://cloud.githubusercontent.com/assets/1085350/10283627/170e7356-6b46-11e5-939b-41584ebb49b6.png)

**Comment by jbondhus** [comment]
According to packages.config though, it's targeting 6.0.2.

![image](https://cloud.githubusercontent.com/assets/1085350/10283666/402c91aa-6b46-11e5-8e36-fca26940a012.png)

**Comment by jbondhus** [comment]
So I removed the packages and installed `Microsoft.AspNet.WebApi.Client` from scratch, which automatically resolved the `Newtonsoft.Json` dependency. Here's the updated package.config file which seems to fix the issue.

```xml
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Microsoft.AspNet.WebApi.Client" version="5.2.3" targetFramework="net45" />
  <package id="Newtonsoft.Json" version="6.0.4" targetFramework="net45" />
</packages>
```

**Comment by srbhk** [comment]
So, if I am using a higher version of Newtonsoft, let's say 9.0.1, will/should ZohoBooks work? Currently, it does not seem to be. I am getting the same TypeInitialization exception.

Is there any way I can make it work with a higher version? Theoretically, should be backwards compatible, no?

Due to certain limitations I cannot use a version lower than 9.0 in my production environment.

Please advise.

Thanks.
